---
- hosts: hosts
  tasks:
    - name: Actualizar repos
      apt: 
       update_cache: yes
    - name: Instalacion de Docker
      apt: name=docker.io 
    - name: Inicio del servicio de docker
      command:
       cmd: systemctl enable docker

